package com.shadow.model;

public enum SkillGroupName {

	ANIMAL_HUSBANDRY, ATHLETICS, BIOTECH, CLOSE_COMBAT, CONJURING, CRACKING, ELECTRONICS, FIREARMS, INFLUENCE, OUTDOORS,
	SORCERY, STEALTH, TASKING;

}
